site_name: Probatus

repo_url: https://github.com/ing-bank/probatus/
site_url: https://ing-bank.github.io/probatus/
site_description: Validation of regressors and classifiers and data used to develop them
site_author: ING Bank N. V.

use_directory_urls: false

watch:
- probatus

plugins:
  - mkdocs-jupyter
  - search
  - mkdocstrings:
      handlers:
          python:
            options:
              selection:
                inherited_members: true
                filters:
                  - "!^Base"
                  - "!^_"  # exlude all members starting with _
                  - "^__init__$"  # but always include __init__ modules and methods
              rendering:
                show_root_toc_entry: false

theme:
  name: material
  logo: img/Probatus_P_white.png
  favicon: img/Probatus_P_white.png
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: deep orange
    accent: indigo

copyright: Copyright &copy; ING Bank N.V.